In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('drug200.csv')

In [3]:
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [4]:
df.isna().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [5]:
df.describe()

              Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [7]:
df.shape

(200, 6)

In [8]:
for col in df.columns:
    print(f"{col}: {df[col].nunique()} unique values")

Age: 57 unique values
Sex: 2 unique values
BP: 3 unique values
Cholesterol: 2 unique values
Na_to_K: 198 unique values
Drug: 5 unique values

In [9]:
categorical_cols = df.select_dtypes(include=['object']).columns

In [10]:
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

In [12]:
for col in categorical_cols:
    print(f"{col}: {df[col].value_counts()}")
    print("\n")

Sex: Sex
M    104
F     96
Name: count, dtype: int64


BP: BP
HIGH      77
LOW       64
NORMAL    59
Name: count, dtype: int64


Cholesterol: Cholesterol
HIGH      103
NORMAL     97
Name: count, dtype: int64


Drug: Drug
DrugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: count, dtype: int64